package com.jarvis.mobile;
import android.Manifest; import android.app.*; import android.app.role.RoleManager; import android.content.*; import android.content.pm.PackageManager; import android.graphics.Color; import android.os.Bundle; import android.provider.Settings; import android.speech.*; import android.speech.tts.TextToSpeech; import android.view.*; import android.widget.*; import java.util.*; import com.jarvis.mobile.brain.JarvisBrain;
public class MainActivity extends Activity implements TextToSpeech.OnInit {
 TextView out; EditText input; SpeechRecognizer sr; TextToSpeech tts; JarvisBrain brain;
 public void onCreate(Bundle b){super.onCreate(b); brain=new JarvisBrain(this); tts=new TextToSpeech(this,this); build(); if(checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED) requestPermissions(new String[]{Manifest.permission.RECORD_AUDIO,Manifest.permission.READ_CONTACTS,Manifest.permission.CALL_PHONE},7);}
 void build(){ FrameLayout root=new FrameLayout(this); root.setBackgroundResource(com.jarvis.mobile.R.drawable.background_mk3); LinearLayout box=new LinearLayout(this); box.setOrientation(LinearLayout.VERTICAL); box.setPadding(32,70,32,32); ImageView r=new ImageView(this); r.setImageResource(R.drawable.ic_reactor); box.addView(r,new LinearLayout.LayoutParams(-1,260)); out=new TextView(this); out.setTextColor(Color.CYAN); out.setTextSize(18); out.setText("JARVIS online. Tap LISTEN or type a command."); box.addView(out,new LinearLayout.LayoutParams(-1,0,1)); input=new EditText(this); input.setTextColor(Color.WHITE); input.setHintTextColor(Color.LTGRAY); input.setHint("Command..."); box.addView(input); Button go=new Button(this); go.setText("RUN"); go.setOnClickListener(v->run(input.getText().toString())); box.addView(go); Button listen=new Button(this); listen.setText("LISTEN"); listen.setOnClickListener(v->listen()); box.addView(listen); Button asst=new Button(this); asst.setText("MAKE JARVIS DEFAULT ASSISTANT"); asst.setOnClickListener(v->assistantRole()); box.addView(asst); Button access=new Button(this); access.setText("ENABLE DEVICE CONTROL"); access.setOnClickListener(v->startActivity(new Intent(Settings.ACTION_ACCESSIBILITY_SETTINGS))); box.addView(access); root.addView(box); setContentView(root); }
 void run(String q){ if(q==null||q.trim().isEmpty())return; String a=brain.handle(q); out.setText("You: "+q+"\n\nJARVIS: "+a); if(tts!=null)tts.speak(a,TextToSpeech.QUEUE_FLUSH,null,"jarvis"); }
 void listen(){ if(!SpeechRecognizer.isRecognitionAvailable(this)){out.setText("Speech recognition unavailable.");return;} if(sr!=null)sr.destroy(); sr=SpeechRecognizer.createSpeechRecognizer(this); sr.setRecognitionListener(new RecognitionListener(){ public void onResults(Bundle b){ArrayList<String>x=b.getStringArrayList(SpeechRecognizer.RESULTS_RECOGNITION); if(x!=null&&!x.isEmpty())run(x.get(0));} public void onError(int e){out.setText("Listening error "+e);} public void onReadyForSpeech(Bundle b){} public void onBeginningOfSpeech(){} public void onRmsChanged(float f){} public void onBufferReceived(byte[] b){} public void onEndOfSpeech(){} public void onPartialResults(Bundle b){} public void onEvent(int t,Bundle b){} }); Intent i=new Intent(RecognizerIntent.ACTION_RECOGNIZE_SPEECH); i.putExtra(RecognizerIntent.EXTRA_LANGUAGE_MODEL,RecognizerIntent.LANGUAGE_MODEL_FREE_FORM); sr.startListening(i); out.setText("Listening..."); }
 void assistantRole(){ RoleManager rm=getSystemService(RoleManager.class); if(rm!=null&&rm.isRoleAvailable(RoleManager.ROLE_ASSISTANT)) startActivityForResult(rm.createRequestRoleIntent(RoleManager.ROLE_ASSISTANT),9); }
 public void onInit(int s){if(s==TextToSpeech.SUCCESS)tts.setLanguage(Locale.US);} public void onDestroy(){super.onDestroy(); if(sr!=null)sr.destroy(); if(tts!=null)tts.shutdown();}
}
