package com.jarvis.mobile.assistant;

import android.Manifest;import android.content.*;import android.content.pm.PackageManager;import android.graphics.*;import android.os.*;import android.service.voice.VoiceInteractionSession;import android.speech.*;import android.speech.tts.TextToSpeech;import android.util.Log;import android.view.*;import android.widget.*;
import com.jarvis.brain.*;import com.jarvis.mobile.MainActivity;import com.jarvis.mobile.R;import com.jarvis.mobile.brain.AndroidBrainRuntime;import java.util.*;

public class JarvisVoiceSession extends VoiceInteractionSession implements TextToSpeech.OnInitListener{
 private AndroidBrainRuntime brain;private SpeechRecognizer speechRecognizer;private TextToSpeech textToSpeech;private ImageView background,face;private TextView output;private Button primaryButton,cancelButton;private boolean viewReady,autoListenTriggered;private String lastCommand="";
 public JarvisVoiceSession(Context context){super(context);}
 @Override public void onCreate(){super.onCreate();brain=new AndroidBrainRuntime(getContext());textToSpeech=new TextToSpeech(getContext(),this);}
 @Override public View onCreateContentView(){Log.i("JARVIS_ASSISTANT_TEST","JARVIS_ASSISTANT_READY");FrameLayout root=new FrameLayout(getContext());background=new ImageView(getContext());background.setImageResource(R.drawable.background_mk3_active);background.setScaleType(ImageView.ScaleType.CENTER_CROP);root.addView(background,new FrameLayout.LayoutParams(-1,-1));face=new ImageView(getContext());face.setImageResource(R.drawable.jarvis_normal);face.setScaleType(ImageView.ScaleType.CENTER_INSIDE);FrameLayout.LayoutParams fp=new FrameLayout.LayoutParams(dp(120),dp(120),Gravity.CENTER_HORIZONTAL|Gravity.TOP);fp.topMargin=dp(48);root.addView(face,fp);output=new TextView(getContext());output.setText("Listening…");output.setTextColor(Color.WHITE);output.setTextSize(16);output.setGravity(Gravity.CENTER);output.setShadowLayer(5f,0f,1f,Color.BLACK);output.setPadding(dp(18),dp(12),dp(18),dp(12));FrameLayout.LayoutParams op=new FrameLayout.LayoutParams(-1,-2,Gravity.BOTTOM|Gravity.CENTER_HORIZONTAL);op.bottomMargin=dp(112);root.addView(output,op);LinearLayout buttons=new LinearLayout(getContext());buttons.setGravity(Gravity.CENTER);Button listen=button("LISTEN");listen.setOnClickListener(v->startListening());buttons.addView(listen);primaryButton=button("APPROVE");primaryButton.setVisibility(View.GONE);primaryButton.setOnClickListener(v->deliver(brain.approvePresentation()));buttons.addView(primaryButton);cancelButton=button("NOT YET");cancelButton.setVisibility(View.GONE);cancelButton.setOnClickListener(v->deliver(brain.cancelPresentation()));buttons.addView(cancelButton);Button open=button("OPEN FULL JARVIS");open.setOnClickListener(v->getContext().startActivity(new Intent(getContext(),MainActivity.class).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)));buttons.addView(open);FrameLayout.LayoutParams bp=new FrameLayout.LayoutParams(-1,-2,Gravity.BOTTOM|Gravity.CENTER_HORIZONTAL);bp.bottomMargin=dp(10);root.addView(buttons,bp);viewReady=true;root.postDelayed(this::triggerAutoListen,180);return root;}
 @Override public void onShow(Bundle args,int flags){super.onShow(args,flags);if(viewReady&&output!=null)output.postDelayed(this::triggerAutoListen,120);}
 private void triggerAutoListen(){if(autoListenTriggered)return;autoListenTriggered=true;startListening();}
 private void startListening(){if(getContext().checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED){output.setText("Open JARVIS once and grant Microphone permission.");setActive(false);return;}if(!SpeechRecognizer.isRecognitionAvailable(getContext())){output.setText("Android speech recognition is unavailable.");setActive(false);return;}if(speechRecognizer!=null)speechRecognizer.destroy();speechRecognizer=Build.VERSION.SDK_INT>=31&&SpeechRecognizer.isOnDeviceRecognitionAvailable(getContext())?SpeechRecognizer.createOnDeviceSpeechRecognizer(getContext()):SpeechRecognizer.createSpeechRecognizer(getContext());speechRecognizer.setRecognitionListener(new RecognitionListener(){public void onReadyForSpeech(Bundle p){output.setText("Listening…");setActive(true);}public void onBeginningOfSpeech(){if(textToSpeech!=null)textToSpeech.stop();output.setText("I’m listening.");}public void onRmsChanged(float x){}public void onBufferReceived(byte[]b){}public void onEndOfSpeech(){output.setText("Thinking…");}public void onError(int e){output.setText(e==SpeechRecognizer.ERROR_NO_MATCH||e==SpeechRecognizer.ERROR_SPEECH_TIMEOUT?"I didn’t catch that. Tap LISTEN to try again.":"Listening stopped. Tap LISTEN to try again.");setActive(false);}public void onResults(Bundle r){ArrayList<String>m=r.getStringArrayList(SpeechRecognizer.RESULTS_RECOGNITION);if(m==null||m.isEmpty()){output.setText("I didn’t catch that.");setActive(false);return;}execute(m.get(0));}public void onPartialResults(Bundle p){ArrayList<String>x=p.getStringArrayList(SpeechRecognizer.RESULTS_RECOGNITION);if(x!=null&&!x.isEmpty())output.setText(x.get(0));}public void onEvent(int t,Bundle p){}});Intent i=new Intent(RecognizerIntent.ACTION_RECOGNIZE_SPEECH);i.putExtra(RecognizerIntent.EXTRA_LANGUAGE_MODEL,RecognizerIntent.LANGUAGE_MODEL_FREE_FORM);i.putExtra(RecognizerIntent.EXTRA_LANGUAGE,Locale.getDefault());i.putExtra(RecognizerIntent.EXTRA_PARTIAL_RESULTS,true);speechRecognizer.startListening(i);}
 private void execute(String command){lastCommand=command==null?"":command;output.setText("YOU: "+lastCommand+"\n\nJARVIS: Thinking…");deliver(brain.handlePresentation(lastCommand));}
 private void deliver(RuntimeSurfacePresentation p){String text=p.text(),detail=p.detail(),rendered=text;if(!detail.isBlank()&&!detail.equals(text))rendered+="\n\n"+detail;output.setText((lastCommand.isBlank()?"":"YOU: "+lastCommand+"\n\n")+"JARVIS: "+rendered);boolean approval=p.state()==AssistantSurfaceState.AWAITING_APPROVAL,recovery=p.state()==AssistantSurfaceState.NEEDS_INPUT;primaryButton.setVisibility(approval||recovery?View.VISIBLE:View.GONE);primaryButton.setText(recovery?"RETRY":"APPROVE");primaryButton.setOnClickListener(v->deliver(recovery?brain.retryPresentation():brain.approvePresentation()));cancelButton.setVisibility(approval||recovery?View.VISIBLE:View.GONE);if(!text.isBlank()&&textToSpeech!=null)textToSpeech.speak(text,TextToSpeech.QUEUE_FLUSH,null,"jarvis-session");setActive(false);}
 private void setActive(boolean a){if(face!=null)face.setImageResource(a?R.drawable.jarvis_active:R.drawable.jarvis_normal);if(background!=null)background.setImageResource(a?R.drawable.background_mk3_active:R.drawable.background_mk3);}
 private Button button(String label){Button b=new Button(getContext());b.setText(label);b.setTextColor(Color.rgb(115,235,255));b.setTextSize(11);b.setTypeface(Typeface.MONOSPACE,Typeface.BOLD);b.setBackgroundColor(Color.argb(220,3,30,40));return b;}private int dp(int v){return Math.round(v*getContext().getResources().getDisplayMetrics().density);}
 @Override public void onInit(int s){if(s==TextToSpeech.SUCCESS&&textToSpeech!=null){textToSpeech.setLanguage(Locale.getDefault());textToSpeech.setSpeechRate(.95f);}}
 @Override public void onDestroy(){if(speechRecognizer!=null)speechRecognizer.destroy();if(textToSpeech!=null)textToSpeech.shutdown();super.onDestroy();}
}
