package com.jarvis.brain;

import java.util.*;

public final class AssistantCore {
 private static final int MAX_DIALOGUE_MESSAGES=12,EXECUTIVE_MAX_ITERATIONS=4;
 private static final java.util.regex.Pattern EXPLICIT_WAKE=java.util.regex.Pattern.compile("(?i)^\\s*(?:hey\\s+)?jarvis[,:]?\\s*");
 private final BrainEngine reflex; private final ReasoningRouter providers; private final ToolRegistry tools; private final PlanValidator planValidator; private final PlanExecutionClassifier executionClassifier; private final AssistantContextSource contextSource; private final SemanticGoalInterpreter semanticReflex=new SemanticGoalInterpreter(); private final Deque<String> dialogue=new ArrayDeque<>(); private final ConversationWorkingMemory workingMemory=new ConversationWorkingMemory(); private PendingClarification pendingClarification;
 public AssistantCore(BrainEngine reflex,ProviderRouter providers){this(reflex,providers,ToolRegistry.standard(),AssistantContextSource.none());} public AssistantCore(BrainEngine reflex,ReasoningRouter providers,ToolRegistry tools){this(reflex,providers,tools,AssistantContextSource.none());}
 public AssistantCore(BrainEngine reflex,ReasoningRouter providers,ToolRegistry tools,AssistantContextSource contextSource){if(reflex==null)throw new IllegalArgumentException("brain engine required");if(providers==null)throw new IllegalArgumentException("reasoning router required");this.reflex=reflex;this.providers=providers;this.tools=tools==null?ToolRegistry.standard():tools;this.planValidator=new PlanValidator(this.tools);this.executionClassifier=new PlanExecutionClassifier(this.tools);this.contextSource=contextSource==null?AssistantContextSource.none():contextSource;}
 public boolean hasPendingPlan(){return pendingClarification!=null;} public String pendingPlanGoal(){return pendingClarification==null?"":pendingClarification.plan().goal();} void noteDialogueForTest(String role,String text){remember(role,text);}
 public BrainResponse handle(String utterance){
  boolean explicitWake=isExplicitWakeInvocation(utterance);
  if(pendingClarification!=null&&(explicitWake||!reflex.isConversationActive()))pendingClarification=null;
  if(pendingClarification!=null){BrainResponse resumed=handlePendingClarification(utterance);if(resumed!=null)return resumed;}
  BrainResponse response=reflex.handle(utterance);if(response.kind()==BrainResponse.Kind.IGNORED_AMBIENT)return response;workingMemory.observeUserTurn(utterance);remember("USER",utterance);
  if(response.kind()==BrainResponse.Kind.ACTION_PLAN&&response.plan()!=null){PlanValidation v=planValidator.validate(response.plan());if(!v.valid())return validatedPlanResponse(response.plan(),response.text(),response.sessionActive(),response.acceptedWithoutWakeWord(),response.contextSnapshot(),utterance);if(executionClassifier.isPureAutonomousResearch(v.effectivePlan()))return runExecutive(utterance,response.text(),v.effectivePlan(),response.sessionActive(),response.acceptedWithoutWakeWord(),"deterministic-reflex");}
  if(response.kind()!=BrainResponse.Kind.REASONING_REQUIRED){remember("JARVIS",response.text());return response;}
  String durable=contextSource.contextFor(utterance),context=combineContext(dialogueSnapshot(),workingMemory.snapshot(),durable);Plan semantic=semanticReflex.interpret(utterance).orElse(null);
  if(semantic!=null){PlanValidation v=planValidator.validate(semantic);BrainResponse out;if(v.valid()&&executionClassifier.isPureAutonomousResearch(v.effectivePlan()))out=runExecutive(utterance,"I'll check that.",v.effectivePlan(),response.sessionActive(),response.acceptedWithoutWakeWord(),"semantic-reflex");else out=validatedPlanResponse(semantic,"Understood.",response.sessionActive(),response.acceptedWithoutWakeWord(),context,utterance);remember("JARVIS",out.text());return out;}
  ReasoningResult reasoned=providers.reason(new ReasoningRequest(utterance,context,tools.specs()));workingMemory.applyValidated(reasoned.stateDelta(),utterance);BrainResponse out;
  if(reasoned.plan()!=null){PlanValidation v=planValidator.validate(reasoned.plan());if(!v.valid())out=validatedPlanResponse(reasoned.plan(),reasoned.text(),response.sessionActive(),response.acceptedWithoutWakeWord(),context,utterance);else if(executionClassifier.isPureAutonomousResearch(v.effectivePlan()))out=runExecutive(utterance,reasoned.text(),v.effectivePlan(),response.sessionActive(),response.acceptedWithoutWakeWord(),reasoned.providerId());else out=validatedPlanResponse(v.effectivePlan(),reasoned.text(),response.sessionActive(),response.acceptedWithoutWakeWord(),context,utterance);}else out=BrainResponse.of(BrainResponse.Kind.CONVERSATION,reasoned.text(),null,response.sessionActive(),response.acceptedWithoutWakeWord(),context);remember("JARVIS",out.text());return out;
 }
 private BrainResponse runExecutive(String utterance,String text,Plan plan,boolean active,boolean noWake,String provider){String context=combineContext(dialogueSnapshot(),workingMemory.snapshot(),contextSource.contextFor(utterance));ReasoningResult rr=new ReasoningResult(provider,text,plan);ExecutiveOutcome o=new ExecutiveObservationLoop(providers,tools,new ApprovalGate(),EXECUTIVE_MAX_ITERATIONS).runFrom(utterance,context,rr);if(o!=null)workingMemory.applyValidated(o.stateDelta(),utterance);BrainResponse r=executiveResponse(o,active,noWake);remember("JARVIS",r.text());return r;}
 private BrainResponse executiveResponse(ExecutiveOutcome o,boolean active,boolean noWake){if(o==null)return BrainResponse.of(BrainResponse.Kind.CONVERSATION,"I couldn't complete that safely.",null,active,noWake,combinedSessionContext());if(o.status()==ExecutiveOutcome.Status.APPROVAL_REQUIRED)return BrainResponse.of(BrainResponse.Kind.ACTION_PLAN,o.text()==null||o.text().isBlank()?"I need your approval before I do that.":o.text(),o.pendingPlan(),active,noWake,o.context());return BrainResponse.of(BrainResponse.Kind.CONVERSATION,o.text()==null||o.text().isBlank()?"I couldn't complete that safely.":o.text(),null,active,noWake,o.context());}
 private BrainResponse validatedPlanResponse(Plan plan,String text,boolean active,boolean noWake,String context,String originalUtterance){PlanValidation v=planValidator.validate(plan);if(!v.valid()){List<PendingClarification.MissingArgument> missing=findMissingArguments(v.effectivePlan());if(!missing.isEmpty()){pendingClarification=new PendingClarification(v.effectivePlan(),missing,originalUtterance,active,noWake);return BrainResponse.of(BrainResponse.Kind.CONVERSATION,clarificationQuestion(missing.get(0).argument()),null,active,noWake,context);}return BrainResponse.of(BrainResponse.Kind.CONVERSATION,"I need clarification before I can build a safe executable plan: "+String.join("; ",v.errors())+".",null,active,noWake,context);}return BrainResponse.of(BrainResponse.Kind.ACTION_PLAN,text==null||text.isBlank()?"Understood.":text,v.effectivePlan(),active,noWake,context);}
 private BrainResponse handlePendingClarification(String utterance){String a=utterance==null?"":utterance.trim();if(a.isEmpty())return null;PendingClarification s=pendingClarification;if(a.toLowerCase(Locale.ROOT).matches("cancel|never mind|nevermind|forget it|stop")){pendingClarification=null;return BrainResponse.of(BrainResponse.Kind.CONVERSATION,"Cancelled.",null,s.sessionActive(),s.acceptedWithoutWakeWord(),dialogueSnapshot());}Plan filled=fillArgument(s.plan(),s.missing().get(0),a);PlanValidation v=planValidator.validate(filled);List<PendingClarification.MissingArgument> remaining=findMissingArguments(v.effectivePlan());workingMemory.observeUserTurn(a);remember("USER",a);if(v.valid()){pendingClarification=null;if(executionClassifier.isPureAutonomousResearch(v.effectivePlan()))return runExecutive(s.originalUtterance(),"Understood. I have what I need.",v.effectivePlan(),s.sessionActive(),s.acceptedWithoutWakeWord(),"clarification-resume");return BrainResponse.of(BrainResponse.Kind.ACTION_PLAN,"Understood. I have what I need.",v.effectivePlan(),s.sessionActive(),s.acceptedWithoutWakeWord(),combinedSessionContext());}if(!remaining.isEmpty()){pendingClarification=new PendingClarification(v.effectivePlan(),remaining,s.originalUtterance(),s.sessionActive(),s.acceptedWithoutWakeWord());return BrainResponse.of(BrainResponse.Kind.CONVERSATION,clarificationQuestion(remaining.get(0).argument()),null,s.sessionActive(),s.acceptedWithoutWakeWord(),combinedSessionContext());}pendingClarification=null;return BrainResponse.of(BrainResponse.Kind.CONVERSATION,"I still can't make that plan safe to execute.",null,s.sessionActive(),s.acceptedWithoutWakeWord(),combinedSessionContext());}
 private List<PendingClarification.MissingArgument> findMissingArguments(Plan plan){List<PendingClarification.MissingArgument> m=new ArrayList<>();if(plan==null)return m;for(int i=0;i<plan.steps().size();i++){PlanStep s=plan.steps().get(i);ToolRegistry.RegisteredTool r=tools.resolve(s.tool()).orElse(null);if(r!=null)for(String req:r.spec().requiredArguments())if(s.arguments().get(req)==null||s.arguments().get(req).isBlank())m.add(new PendingClarification.MissingArgument(i,req));}return List.copyOf(m);}
 private static Plan fillArgument(Plan p,PendingClarification.MissingArgument t,String value){List<PlanStep>s=new ArrayList<>(p.steps());PlanStep old=s.get(t.stepIndex());Map<String,String>a=new HashMap<>(old.arguments());a.put(t.argument(),value.trim());s.set(t.stepIndex(),new PlanStep(old.tool(),Map.copyOf(a),old.consequential()));return new Plan(p.goal(),List.copyOf(s));}
 private static boolean isExplicitWakeInvocation(String utterance){return utterance!=null&&EXPLICIT_WAKE.matcher(utterance).find();}
 private static String clarificationQuestion(String a){return switch(a){case"destination"->"Where would you like to go?";case"recipient"->"Who should I send it to?";case"message"->"What would you like me to say?";case"business"->"Which business do you mean?";case"when"->"When should I do that?";case"amount"->"How long?";case"unit"->"Seconds, minutes, or hours?";default->"What should I use for "+a.replace('_',' ')+"?";};}
 private void remember(String role,String text){if(text==null||text.isBlank())return;dialogue.addLast(role+": "+text.trim());while(dialogue.size()>MAX_DIALOGUE_MESSAGES)dialogue.removeFirst();} private String dialogueSnapshot(){return String.join("\n",dialogue);} private String combinedSessionContext(){return combineContext(dialogueSnapshot(),workingMemory.snapshot(),"");}
 private static String combineContext(String d,String w,String l){StringBuilder o=new StringBuilder("Response style:\n").append(ResponseStyleContract.beta().guidance());if(d!=null&&!d.isBlank())o.append("\nRecent conversation:\n").append(d.trim());if(w!=null&&!w.isBlank())o.append("\nStructured session memory:\n").append(w.trim());if(l!=null&&!l.isBlank())o.append("\nRelevant durable memory:\n").append(l.trim());return o.toString();}
}
