plugins {
    id 'com.android.application'
}

android {
    namespace 'com.jarvis.mobile'
    compileSdk 36

    defaultConfig {
        applicationId 'com.jarvis.mobile'
        minSdk 29
        targetSdk 36
        versionCode 13
        versionName '1.1-donor-beta3'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildTypes {
        debug {
            debuggable true
        }
        release {
            minifyEnabled false
            shrinkResources false
        }
    }
}
