package com.jarvis.brain;
import java.time.*;import java.util.*;
public final class AssistantExecutiveIntegrationTest{
 private static int checks;
 public static void main(String[]a){safeResearchExecutes();synthesisStateSurvives();consequentialStops();mixedPlanDoesNotAutoExecute();nullExecutiveReasoningResultDegradesSafely();System.out.println("AssistantExecutiveIntegrationTest: "+checks+" assertions passed");}
 private static ToolRegistry dinner(int[]search){ToolRegistry r=new ToolRegistry();r.register(new ToolSpec("discover_places",false,Set.of(),Set.of("category"),"Discover",ToolExecutionClass.AUTONOMOUS_RESEARCH),(x,c)->{search[0]++;return ToolResult.success("Castle Cafe");});r.register(new ToolSpec("rank_options",false,Set.of(),Set.of(),"Rank",ToolExecutionClass.AUTONOMOUS_RESEARCH),(x,c)->ToolResult.success("Castle Cafe"));r.register(new ToolSpec("present_options",false,Set.of(),Set.of(),"Present",ToolExecutionClass.AUTONOMOUS_RESEARCH),(x,c)->ToolResult.success("Castle Cafe"));return r;}
 private static BrainEngine brain(){return BrainEngine.createDefault(Clock.fixed(Instant.parse("2026-08-28T04:00:00Z"),ZoneOffset.UTC));}
 private static void safeResearchExecutes(){int[]s={0};ToolRegistry r=dinner(s);ReasoningRouter q=req->new ReasoningResult("local","Castle Cafe",null);AssistantCore c=new AssistantCore(brain(),q,r);c.handle("Hey Jarvis");BrainResponse x=c.handle("find me somewhere to eat for dinner tonight");check(x.kind()==BrainResponse.Kind.CONVERSATION,"pure research executes");check(s[0]==1,"research once");}
 private static void synthesisStateSurvives(){int[]s={0},n={0};ToolRegistry r=dinner(s);ReasoningRouter q=req->{n[0]++;if(n[0]==1)return new ReasoningResult("local","Castle Cafe",null,new SessionStateDelta("find dinner","dinner",Map.of(),"","","Castle Cafe best",false));check(req.context().contains("Castle Cafe best"),"state survives");return new ReasoningResult("local","still Castle Cafe",null);};AssistantCore c=new AssistantCore(brain(),q,r);c.handle("Hey Jarvis");c.handle("find me somewhere to eat for dinner tonight");c.handle("compare that choice against another option");check(n[0]==2,"two reason calls");}
 private static void consequentialStops(){ToolRegistry r=new ToolRegistry();int[]send={0};r.register(new ToolSpec("send_message",true,Set.of(),Set.of("recipient","message"),"send"),(x,c)->{send[0]++;return ToolResult.success("sent");});ReasoningRouter q=req->new ReasoningResult("local","approve",new Plan("send",List.of(new PlanStep("send_message",Map.of("recipient","Mom","message","late"),true))));AssistantCore c=new AssistantCore(brain(),q,r);c.handle("Hey Jarvis");BrainResponse x=c.handle("tell Mom I'm late");check(x.kind()==BrainResponse.Kind.ACTION_PLAN&&send[0]==0,"consequential remains approval-bound");}
 private static void mixedPlanDoesNotAutoExecute(){ToolRegistry r=new ToolRegistry();int[]research={0},device={0};r.register(new ToolSpec("research",false,Set.of(),Set.of(),"r",ToolExecutionClass.AUTONOMOUS_RESEARCH),(x,c)->{research[0]++;return ToolResult.success("fact");});r.register(new ToolSpec("device",false,Set.of(),Set.of(),"d",ToolExecutionClass.DEVICE_REFLEX),(x,c)->{device[0]++;return ToolResult.success("done");});ReasoningRouter q=req->new ReasoningResult("local","mixed",new Plan("mixed",List.of(new PlanStep("research",Map.of(),false),new PlanStep("device",Map.of(),false))));AssistantCore c=new AssistantCore(brain(),q,r);c.handle("Hey Jarvis");BrainResponse x=c.handle("do mixed work");check(x.kind()==BrainResponse.Kind.ACTION_PLAN,"mixed plan stays explicit instead of wholesale autonomous route");check(research[0]==0&&device[0]==0,"mixed route executes nothing before explicit dispatcher");}
 private static void nullExecutiveReasoningResultDegradesSafely(){int[]s={0};ToolRegistry r=dinner(s);ReasoningRouter q=req->null;AssistantCore c=new AssistantCore(brain(),q,r);c.handle("Hey Jarvis");BrainResponse x;try{x=c.handle("find me somewhere to eat for dinner tonight");}catch(RuntimeException escaped){throw new AssertionError("null autonomous executive reasoning result must not escape AssistantCore",escaped);}check(x.kind()==BrainResponse.Kind.CONVERSATION,"null executive reasoning result should become a truthful conversation response");check(x.text()!=null&&x.text().toLowerCase(Locale.ROOT).contains("couldn't"),"null executive reasoning result should say the task was not completed");check(s[0]==1,"safe research may complete before synthesis failure, but must not be replayed");}
 private static void check(boolean v,String m){checks++;if(!v)throw new AssertionError(m);}
}