package com.jarvis.brain;

import java.time.Clock;
import java.time.Instant;
import java.time.ZoneOffset;

public final class AssistantBenchmarkTest {
    private static int passed;
    public static void main(String[] args) { commonAssistantRequestsResolveToTools(); deterministicMathAnswersWithoutModel(); weatherFollowupKeepsLocationContext(); messageRequiresApproval(); personalMemoryCanBeWrittenAndRecalled(); unsupportedLanguageStillRoutesToReasoning(); System.out.println("PASS " + passed + " assistant benchmark assertions"); }
    private static BrainEngine engine() { return BrainEngine.createDefault(Clock.fixed(Instant.parse("2026-08-27T23:30:00Z"), ZoneOffset.UTC)); }
    private static void commonAssistantRequestsResolveToTools() { BrainEngine brain = engine(); brain.handle("Hey Jarvis"); assertTool(brain.handle("what's the weather like tonight?"), "weather_lookup"); assertTool(brain.handle("set a timer for 20 minutes"), "set_timer"); check(brain.handle("remind me to call mom tomorrow at 10").kind() == BrainResponse.Kind.REASONING_REQUIRED, "timed reminder needs cortex to resolve structured title + start_millis"); assertTool(brain.handle("navigate to the nearest gas station"), "navigate"); assertTool(brain.handle("play some jazz"), "media_play"); assertTool(brain.handle("turn the flashlight on"), "set_flashlight"); assertTool(brain.handle("what's on my calendar tomorrow"), "calendar_query"); assertTool(brain.handle("what notifications did I miss"), "notification_query"); assertTool(brain.handle("translate hello to Spanish"), "translate"); }
    private static void deterministicMathAnswersWithoutModel() { BrainEngine brain = engine(); brain.handle("Hey Jarvis"); BrainResponse response = brain.handle("what is 17 times 24"); check(response.kind() == BrainResponse.Kind.CONVERSATION, "simple math should answer directly"); check(response.text().contains("408"), "17 times 24 must equal 408"); }
    private static void weatherFollowupKeepsLocationContext() { BrainEngine brain = engine(); brain.handle("Hey Jarvis"); BrainResponse first = brain.handle("what's the weather in Castle Rock tomorrow?"); assertTool(first, "weather_lookup"); check(first.plan().steps().get(0).arguments().get("location").contains("Castle Rock"), "weather request should extract location"); BrainResponse follow = brain.handle("what about Friday?"); assertTool(follow, "weather_lookup"); check(follow.plan().steps().get(0).arguments().get("location").contains("Castle Rock"), "weather follow-up should keep previous location"); }
    private static void messageRequiresApproval() { BrainEngine brain = engine(); brain.handle("Hey Jarvis"); BrainResponse response = brain.handle("text mom I'm on my way"); assertTool(response, "send_message"); check(response.plan().requiresApproval(), "sending a message is consequential and requires approval"); }
    private static void personalMemoryCanBeWrittenAndRecalled() { BrainEngine brain = engine(); brain.handle("Hey Jarvis"); BrainResponse write = brain.handle("remember my favorite coffee is a flat white"); check(write.kind() == BrainResponse.Kind.CONVERSATION, "remember should acknowledge conversationally"); BrainResponse read = brain.handle("what's my favorite coffee?"); check(read.text().toLowerCase().contains("flat white"), "brain should recall personal memory within session"); }
    private static void unsupportedLanguageStillRoutesToReasoning() { BrainEngine brain = engine(); brain.handle("Hey Jarvis"); BrainResponse response = brain.handle("help me decide whether I should reorganize my whole week"); check(response.kind() == BrainResponse.Kind.REASONING_REQUIRED, "complex open-ended request should route to cortex"); }
    private static void assertTool(BrainResponse response, String tool) { check(response.kind() == BrainResponse.Kind.ACTION_PLAN, "expected action plan for " + tool + " but got " + response.kind()); check(response.plan().steps().stream().anyMatch(s -> s.tool().equals(tool)), "expected tool " + tool); }
    private static void check(boolean condition, String message) { if (!condition) throw new AssertionError(message); passed++; }
}
