package com.jarvis.brain;
import java.lang.reflect.*; import java.util.List;
/** Cross-cutting JVM brain exit gate; Android/device readiness remains separate. */
public final class BrainExitGateAcceptanceTest {
 private static final List<Class<?>> GATES=List.of(BrainAcceptanceTest.class,BrainAdvancedAcceptanceTest.class,BrainProviderAcceptanceTest.class,AssistantBenchmarkTest.class,AssistantExecutiveIntegrationTest.class,ConversationContinuityTest.class,PendingClarificationTest.class,PlanStateAndRetentionTest.class,ResumableExecutionTest.class,ExecutionRecoveryContractTest.class,ExecutiveObservationLoopTest.class,ExternalResearchGatewayContractTest.class,SessionTrustBoundaryTest.class,SessionStateDeltaTest.class,ProviderAttemptBudgetTest.class,ProviderRecoveryTest.class,ProductionSafetyContractTest.class,ProactiveSafetyPolicyTest.class,EpisodeFollowupPolicyTest.class,WakeBargeInCompositionTest.class,ToolCapableLocalProviderTest.class,ToolContractSelectorTest.class,ToolExecutionClassTest.class,PlanExecutionClassifierTest.class,GoalInterruptionPolicyTest.class,ExecutiveTaskControlTest.class,ExecutiveSessionStateTest.class,InterruptionCoordinatorTest.class,OutcomeFeedbackMemoryTest.class,StructuredDiningFeedbackTest.class,DiningResearchCapabilityTest.class,MenuPriceQuoteTest.class,ConnectionRegistryTest.class,ConnectionManagerTest.class,ManualMemoryEditorTest.class,LongTermMemoryTest.class,MemoryConsolidationTest.class,MemoryLifecycleTest.class);
 private BrainExitGateAcceptanceTest(){}
 public static void main(String[]a)throws Exception{int p=0;for(Class<?>g:GATES){run(g);p++;}if(p!=GATES.size())throw new AssertionError("Brain exit gate did not execute every required acceptance contract");System.out.println("BrainExitGateAcceptanceTest: PASS ("+p+" composed gates)");System.out.println("NOTE: composed JVM brain verified; Android/device smoke still required separately.");}
 private static void run(Class<?>g)throws Exception{try{g.getMethod("main",String[].class).invoke(null,(Object)new String[0]);}catch(InvocationTargetException e){Throwable c=e.getCause();if(c instanceof Exception x)throw x;if(c instanceof Error x)throw x;throw new RuntimeException("Acceptance gate failed: "+g.getSimpleName(),c);}}
}
