package com.jarvis.brain;

import java.time.Instant;
import java.util.List;
import java.util.Set;

public final class LongTermMemoryTest {
    private static int passed;
    public static void main(String[] args) { preferenceIsRetrievedByMeaningfulQueryTerms(); updatedPreferenceSupersedesOldWithoutDeletingHistory(); routinesAccumulateEvidenceInsteadOfDuplicatingBlindly(); importantStableMemoriesOutrankIncidentalEpisodes(); lowConfidenceInferenceDoesNotMasqueradeAsUserStatedFact(); episodicHistoryRemainsSearchableAfterSupersession(); memoryPackBuildsCompactRelevantContext(); memoryPackPreservesSourceProvenance(); System.out.println("PASS " + passed + " long-term memory assertions"); }
    private static void preferenceIsRetrievedByMeaningfulQueryTerms() { LongTermMemoryStore store = new LongTermMemoryStore(); store.put(new RichMemory("food.italian", MemoryType.PREFERENCE, "User prefers Italian food for dinner", "user-stated", 1.0, 0.85, Instant.parse("2026-08-01T00:00:00Z"), null, Set.of("food", "dinner", "italian"))); List<RichMemory> found = store.retrieve("where should we eat dinner", Instant.parse("2026-08-27T00:00:00Z"), 5); check(found.stream().anyMatch(m -> m.key().equals("food.italian")), "dinner query should retrieve relevant food preference"); }
    private static void updatedPreferenceSupersedesOldWithoutDeletingHistory() { LongTermMemoryStore store = new LongTermMemoryStore(); store.put(new RichMemory("coffee.default", MemoryType.PREFERENCE, "latte", "user-stated", 1.0, 0.7, Instant.parse("2026-01-01T00:00:00Z"), null, Set.of("coffee"))); store.put(new RichMemory("coffee.default", MemoryType.PREFERENCE, "flat white", "user-stated", 1.0, 0.8, Instant.parse("2026-08-01T00:00:00Z"), null, Set.of("coffee"))); check(store.current("coffee.default", Instant.parse("2026-08-27T00:00:00Z")).orElseThrow().content().equals("flat white"), "new preference should become current"); check(store.history("coffee.default").size() == 2, "old preference should remain historical rather than be erased"); check(store.history("coffee.default").get(0).validUntil() != null, "superseded fact should be closed temporally"); }
    private static void routinesAccumulateEvidenceInsteadOfDuplicatingBlindly() { LongTermMemoryStore store = new LongTermMemoryStore(); Instant now = Instant.parse("2026-08-27T00:00:00Z"); store.observeRoutine("gym.after_work", "Usually opens gym app after work Monday/Wednesday", Set.of("gym", "after_work"), now); store.observeRoutine("gym.after_work", "Usually opens gym app after work Monday/Wednesday", Set.of("gym", "after_work"), now.plusSeconds(3600)); RichMemory routine = store.current("gym.after_work", now.plusSeconds(7200)).orElseThrow(); check(routine.evidenceCount() == 2, "routine observations should accumulate evidence"); check(store.history("gym.after_work").size() == 1, "same routine evidence should not create duplicate memories"); }
    private static void importantStableMemoriesOutrankIncidentalEpisodes() { LongTermMemoryStore store = new LongTermMemoryStore(); Instant now = Instant.parse("2026-08-27T00:00:00Z"); store.put(new RichMemory("preference.quiet_restaurant", MemoryType.PREFERENCE, "Prefers quieter restaurants", "user-stated", 1.0, 0.95, now.minusSeconds(86400 * 30), null, Set.of("restaurant", "quiet", "dinner"))); store.put(new RichMemory("episode.restaurant_noise", MemoryType.EPISODE, "Walked past a loud restaurant yesterday", "observed", 0.8, 0.25, now.minusSeconds(86400), null, Set.of("restaurant", "loud", "dinner"))); List<RichMemory> results = store.retrieve("restaurant for dinner", now, 2); check(results.get(0).key().equals("preference.quiet_restaurant"), "stable important preference should outrank incidental episode"); }
    private static void lowConfidenceInferenceDoesNotMasqueradeAsUserStatedFact() { LongTermMemoryStore store = new LongTermMemoryStore(); Instant now = Instant.parse("2026-08-27T00:00:00Z"); store.put(new RichMemory("inferred.breakfast", MemoryType.INFERENCE, "May prefer breakfast at 9", "inferred", 0.42, 0.4, now, null, Set.of("breakfast"))); check(store.currentTrusted("inferred.breakfast", now, 0.75).isEmpty(), "low-confidence inference should not be treated as trusted fact"); }
    private static void episodicHistoryRemainsSearchableAfterSupersession() { LongTermMemoryStore store = new LongTermMemoryStore(); Instant now = Instant.parse("2026-08-27T00:00:00Z"); store.put(new RichMemory("home.city", MemoryType.FACT, "Denver", "user-stated", 1.0, 0.9, now.minusSeconds(86400 * 100), null, Set.of("home", "city", "denver"))); store.put(new RichMemory("home.city", MemoryType.FACT, "Castle Rock", "user-stated", 1.0, 0.9, now.minusSeconds(86400 * 20), null, Set.of("home", "city", "castle", "rock"))); check(store.searchHistory("Denver", 5).stream().anyMatch(m -> m.content().equals("Denver")), "historical superseded facts should remain searchable"); }
    private static void memoryPackBuildsCompactRelevantContext() { LongTermMemoryStore store = new LongTermMemoryStore(); Instant now = Instant.parse("2026-08-27T00:00:00Z"); store.put(new RichMemory("food.italian", MemoryType.PREFERENCE, "Prefers Italian dinner", "user-stated", 1.0, 0.9, now.minusSeconds(1000), null, Set.of("food", "italian", "dinner"))); store.put(new RichMemory("unrelated.keyboard", MemoryType.FACT, "Owns a mechanical keyboard", "user-stated", 1.0, 0.4, now.minusSeconds(1000), null, Set.of("keyboard"))); String pack = store.memoryPack("find dinner", now, 3); check(pack.contains("Italian"), "memory pack should contain relevant preference"); check(!pack.contains("mechanical keyboard"), "memory pack should omit irrelevant detail"); }
    private static void memoryPackPreservesSourceProvenance() { LongTermMemoryStore store = new LongTermMemoryStore(); Instant now = Instant.parse("2026-08-27T00:00:00Z"); store.put(new RichMemory("inferred.breakfast", MemoryType.INFERENCE, "May prefer breakfast at 9", "inferred-unconfirmed", 0.42, 0.5, now, null, Set.of("breakfast"))); String pack = store.memoryPack("breakfast", now, 3); check(pack.contains("source=inferred-unconfirmed"), "provider-facing memory context must preserve that an inference is unconfirmed"); }
    private static void check(boolean condition, String message) { if (!condition) throw new AssertionError(message); passed++; }
}
