package com.jarvis.brain;

import java.nio.file.Files;
import java.time.Instant;
import java.util.List;

public final class MemoryConsolidationTest {
    private static int passed;
    public static void main(String[] args) throws Exception { explicitPreferenceBecomesTrustedMemory(); explicitRememberWrapperPreservesStructuredFact(); lowConfidenceSpeechStaysUnconfirmed(); namedRelationshipFactIsExtracted(); correctionSupersedesPriorPreference(); repeatedBehaviorBecomesRoutineOnlyAfterEvidenceThreshold(); oneOffBehaviorDoesNotBecomeRoutine(); richMemoryPersistsAndReloadsWithHistory(); extractionDoesNotPersistWholeTranscriptByDefault(); System.out.println("PASS " + passed + " memory consolidation assertions"); }
    private static void explicitPreferenceBecomesTrustedMemory() { MemoryConsolidator c = new MemoryConsolidator(new RuleMemoryExtractor(), new LongTermMemoryStore()); Instant now = Instant.parse("2026-08-27T00:00:00Z"); c.ingestUserTurn("I prefer Italian food for dinner", now); RichMemory memory = c.store().retrieve("dinner food", now, 3).get(0); check(memory.type() == MemoryType.PREFERENCE, "explicit preference should be typed as preference"); check(memory.source().equals("user-stated") && memory.confidence() == 1.0, "explicit preference should be trusted user-stated memory"); }
    private static void explicitRememberWrapperPreservesStructuredFact() { MemoryConsolidator c = new MemoryConsolidator(new RuleMemoryExtractor(), new LongTermMemoryStore()); Instant now = Instant.parse("2026-08-30T00:00:00Z"); c.ingestUserTurn("Remember that my gate code is 2468", now); RichMemory memory = c.store().retrieve("gate code", now.plusSeconds(1), 3).stream().findFirst().orElseThrow(() -> new AssertionError("advertised 'remember that' phrasing should reach encrypted durable memory")); check(memory.content().contains("2468"), "remember wrapper must preserve the structured fact value"); check(memory.source().equals("user-stated") && memory.confidence() == 1.0, "explicit remember statement must remain trusted user-stated memory"); }
    private static void lowConfidenceSpeechStaysUnconfirmed() { MemoryConsolidator c = new MemoryConsolidator(new RuleMemoryExtractor(), new LongTermMemoryStore()); Instant now = Instant.parse("2026-08-27T00:00:00Z"); c.ingestUserTurn("My favorite coffee is cortado", 0.62, now); RichMemory memory = c.store().current("preference.favorite_coffee", now).orElseThrow(); check(memory.source().equals("inferred-unconfirmed"), "low-confidence ASR must not masquerade as user-stated truth"); check(memory.confidence() <= 0.70, "low-confidence ASR must remain below trusted-memory confidence"); }
    private static void namedRelationshipFactIsExtracted() { MemoryConsolidator c = new MemoryConsolidator(new RuleMemoryExtractor(), new LongTermMemoryStore()); Instant now = Instant.parse("2026-08-27T00:00:00Z"); c.ingestUserTurn("My sister's name is Sophie", now); List<RichMemory> results = c.store().retrieve("sister Sophie", now, 5); check(results.stream().anyMatch(m -> m.type() == MemoryType.RELATIONSHIP && m.content().contains("Sophie")), "relationship fact should be extracted"); }
    private static void correctionSupersedesPriorPreference() { MemoryConsolidator c = new MemoryConsolidator(new RuleMemoryExtractor(), new LongTermMemoryStore()); Instant first = Instant.parse("2026-08-01T00:00:00Z"); c.ingestUserTurn("My favorite coffee is latte", first); c.ingestUserTurn("Actually my favorite coffee is flat white", first.plusSeconds(86400)); RichMemory current = c.store().retrieve("favorite coffee", first.plusSeconds(172800), 1).get(0); check(current.content().toLowerCase().contains("flat white"), "correction should become current preference"); check(c.store().searchHistory("latte", 10).stream().anyMatch(m -> m.content().toLowerCase().contains("latte")), "old corrected preference should remain historical"); }
    private static void repeatedBehaviorBecomesRoutineOnlyAfterEvidenceThreshold() { MemoryConsolidator c = new MemoryConsolidator(new RuleMemoryExtractor(), new LongTermMemoryStore()); Instant now = Instant.parse("2026-08-27T00:00:00Z"); c.observeBehavior("opens gym app after work", "after_work", now); c.observeBehavior("opens gym app after work", "after_work", now.plusSeconds(86400 * 7)); c.observeBehavior("opens gym app after work", "after_work", now.plusSeconds(86400 * 14)); check(c.store().retrieve("gym after work", now.plusSeconds(86400 * 15), 5).stream().anyMatch(m -> m.type() == MemoryType.ROUTINE), "repeated behavior should consolidate into routine"); }
    private static void oneOffBehaviorDoesNotBecomeRoutine() { MemoryConsolidator c = new MemoryConsolidator(new RuleMemoryExtractor(), new LongTermMemoryStore()); Instant now = Instant.parse("2026-08-27T00:00:00Z"); c.observeBehavior("orders sushi", "home", now); check(c.store().retrieve("sushi routine", now.plusSeconds(60), 5).stream().noneMatch(m -> m.type() == MemoryType.ROUTINE), "single behavior must not become a routine"); }
    private static void richMemoryPersistsAndReloadsWithHistory() throws Exception { var file = Files.createTempDirectory("jarvis-rich-memory").resolve("memories.jrm"); LongTermMemoryStore store = new LongTermMemoryStore(); Instant first = Instant.parse("2026-01-01T00:00:00Z"); store.put(new RichMemory("home.city", MemoryType.FACT, "Denver", "user-stated", 1.0, 0.9, first, null, java.util.Set.of("home","city","denver"))); store.put(new RichMemory("home.city", MemoryType.FACT, "Castle Rock", "user-stated", 1.0, 0.9, first.plusSeconds(100), null, java.util.Set.of("home","city","castle","rock"))); RichMemoryPersistence.save(store, file); LongTermMemoryStore reloaded = RichMemoryPersistence.load(file); check(reloaded.history("home.city").size() == 2, "persistence must retain temporal history"); check(reloaded.current("home.city", first.plusSeconds(200)).orElseThrow().content().equals("Castle Rock"), "reload should preserve current fact"); }
    private static void extractionDoesNotPersistWholeTranscriptByDefault() { MemoryConsolidator c = new MemoryConsolidator(new RuleMemoryExtractor(), new LongTermMemoryStore()); Instant now = Instant.parse("2026-08-27T00:00:00Z"); String turn = "I prefer Italian food. Also this is a bunch of incidental chatter that should not become a raw transcript memory."; c.ingestUserTurn(turn, now); check(c.store().searchHistory("incidental chatter", 10).isEmpty(), "memory extraction should store extracted durable facts, not raw transcript by default"); }
    private static void check(boolean condition, String message) { if (!condition) throw new AssertionError(message); passed++; }
}
